// Status constants
const CUSTOMER_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  BLOCKED: 'blocked'
};

const CREDIT_GAP_STATUS = {
  OPEN: 'open',
  RESOLVED: 'resolved'
};

const OFFER_STATUS = {
  PENDING: 'pending',
  ACTIVE: 'active',
  DISBURSED: 'disbursed'
};

const OFFER_STATUS_TRANSITIONS = {
  [OFFER_STATUS.PENDING]: [OFFER_STATUS.ACTIVE, OFFER_STATUS.DISBURSED],
  [OFFER_STATUS.ACTIVE]: [OFFER_STATUS.DISBURSED],
  [OFFER_STATUS.DISBURSED]: []
};

const IMPACT_LEVELS = {
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low'
};

// Error codes
const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INSUFFICIENT_SCORE: 'INSUFFICIENT_SCORE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST'
};

// Validation rules
const VALIDATION_RULES = {
  PAN_REGEX: /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/,
  MOBILE_LENGTH: 10,
  CIBIL_SCORE_MIN: 300,
  CIBIL_SCORE_MAX: 900
};

module.exports = {
  CUSTOMER_STATUS,
  CREDIT_GAP_STATUS,
  OFFER_STATUS,
  OFFER_STATUS_TRANSITIONS,
  IMPACT_LEVELS,
  ERROR_CODES,
  VALIDATION_RULES
};